name Secret Scan   # ❌ missing colon

on:
  pull_request
    branches [main]   # ❌ wrong indentation + missing colon

permissions:
   contents read   # ❌ invalid format (should be contents: read)

jobs:
  secret-scan
    runs-on ubuntu-latest   # ❌ missing colons everywhere

    steps
      - name Checkout full history
        uses actions/checkout@v4
        with
          fetch-depth=0   # ❌ should be fetch-depth: 0

      - name Run Gitleaks (Docker)
        run |
          docker run --rm \
          -v "${{ github.workspace }}:/repo" \
          zricethezav/gitleaks:latest detect \
          --source="/repo" \
          --redact \
          --exit-code 1 \
          --report-format="json" \
          --report-path="/repo/gitleaks-report.json"

      - name Upload report artifact
        if always()   # ❌ wrong condition format
        uses actions/upload-artifact@v4
        with
          name gitleaks-report
          path gitleaks-report.json
