from Config.db import db
from sqlalchemy.sql import func

class Screen(db.Model):
    __tablename__ = 'tbl_screens'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True, nullable=False)
    screen_uuid = db.Column(db.String(255))
    screen_name = db.Column(db.String(255))
    screen_id = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('tbl_publisher_users.id'))
    screen_orientation = db.Column(db.String(255))
    screen_size_width = db.Column(db.Integer)
    screen_size_height = db.Column(db.Integer)
    screen_resolution_width = db.Column(db.Integer)
    screen_resolution_height = db.Column(db.Integer)
    screen_tags = db.Column(db.Text)
    location_id = db.Column(db.Integer, db.ForeignKey('tbl_location_list.id'))
    pid = db.Column(db.Integer, db.ForeignKey('tbl_publisher.id'))
    is_vast_allowed = db.Column(db.Boolean, default=False)
    duration = db.Column(db.Integer)
    min_duration = db.Column(db.Integer)
    max_duration = db.Column(db.Integer)
    loop_duration = db.Column(db.Integer)
    dwell_time = db.Column(db.Integer)
    operation_hours = db.Column(db.Text)
    peak_hours = db.Column(db.Text)
    weekly_footfall = db.Column(db.Integer)
    peak_hour_cost = db.Column(db.Integer)
    non_peak_hour_cost = db.Column(db.Integer)
    non_peak_imp_cost = db.Column(db.Float)
    peak_hour_imp_cost = db.Column(db.Float)
    disallowed_categories = db.Column(db.Text)
    is_active = db.Column(db.Boolean, default=True)
    network_id = db.Column(db.Integer, db.ForeignKey('tbl_network.id'))
    currency_id = db.Column(db.Integer, db.ForeignKey('currency.id'))
    is_publisher_blocked = db.Column(db.Boolean, default=False)
    screen_live_status = db.Column(db.Boolean, default=False)
    last_seen = db.Column(db.DateTime)
    male_ratio = db.Column(db.Integer, default=50)
    female_ratio = db.Column(db.Integer, default=50)
    created_at = db.Column(db.DateTime, server_default=func.now())
    updated_at = db.Column(db.DateTime, server_default=func.now(), onupdate=func.now())

    # Relationships (optional, add these if you need them)
    publisher_user = db.relationship('PublisherUser', backref='screens')
    location = db.relationship('Location', backref='screens')
    publisher = db.relationship('Publisher', backref='screens')
    network = db.relationship('Network', backref='screens')
    currency = db.relationship('Currency', backref='screens')